# supervisor.sh --- INSTALLING THE THING THAT RESTARTS THE SERVER. One
# definition, for every path that installs a service.
#
# Sourced (not executed) by deploy.sh, after pancra.conf, health.sh and
# start.sh, and with $SSH and $HERE set. The fourth of the shared pieces:
# health.sh owns "is it serving?", start.sh owns "make it run", lock.sh owns
# "is anybody else already doing this?" -- and this one owns "and who starts it
# again at four in the morning?".
#
# ---- WHAT WAS THERE BEFORE, WHICH WAS NOTHING ---------------------------
#
# The deploy started the server over ssh and wrote its pid to a file. That is
# the entire arrangement, and it has two holes an operator only ever finds the
# hard way:
#
#   * the server exits and nothing starts it. The pid file goes on naming the
#     dead process, the port stops answering, and the service is down until a
#     human notices and re-runs the deploy.
#   * the board reboots and the server is not there afterwards. No startup
#     script mentioned it, because the deploy was the only thing that had ever
#     started it, and the deploy runs on somebody's laptop.
#
# Both are fixed by one small program on the board (srv/deploy/supervise.sh)
# and one line in the board's own startup script. This file installs both, and
# then CHECKS that what it installed is running -- because "the unit file was
# written" is not "the service comes back", and the difference between those
# two is the whole item.
#
# ---- WHY NOT `systemctl enable` -----------------------------------------
#
# Because the board is not a systemd machine and this repository cannot know
# what any other board is either. The target is a Milk-V Duo running a
# buildroot image with BusyBox init: no systemctl, no unit directory, a
# read-only-ish system partition, and a boot chain that ends in a script
# belonging to the login user. A deployment that wrote a unit file would have
# installed supervision that never runs, and reported success.
#
# So the mechanism is DECLARED, exactly as the front door is (PANCRA_FRONT):
# PANCRA_SUPERVISOR says what supervises this board and PANCRA_BOOT_HOOK says
# where its boot chain can be joined. The default is the one that needs nothing
# from the board at all.
#
# ---- AND WHY THE SUPERVISOR DOES NOT SPELL OUT THE START COMMAND --------
#
# A supervisor is by definition a second thing that starts the server, and the
# obvious way to write one -- a unit file, or a script, with the command in it
# -- is a SECOND COPY of a command that this directory has spent a lot of
# effort reducing to one. The last time there were four, one of them hard-coded
# the port and both pem paths and never recorded the new pid, so every health
# check afterwards asked after a process that had been killed. `make
# deploycheck` fails the build if the start command appears outside start.sh,
# and that check is not worked around here: the watchdog is handed a GENERATED
# copy, emitted by start_template() into the env file below, refreshed by every
# deploy, with the per-start tag left as a placeholder for it to fill in.

# 0 when PANCRA_SUPERVISOR names something this repository can install.
supervisor_declared() {
   case "${PANCRA_SUPERVISOR:-}" in
      watchdog | none) return 0 ;;
      *) return 1 ;;
   esac
}

# EVERYTHING THE BOARD NEEDS, TRANSCRIBED FROM THE CONTRACT. The watchdog runs
# where pancra.conf does not exist; this is how the contract reaches it, and it
# is rewritten by every deploy so it cannot drift from the contract for longer
# than one deployment.
#
# THE START COMMAND COMES LAST and comes from start_template(), so the board's
# copy is generated rather than written. See the note at the top.
supervisor_env_block() {
   cat <<EOF
# Generated by srv/deploy/supervisor.sh from srv/deploy/pancra.conf. Do not
# edit: the next deploy overwrites it, and the values here have to agree with
# the ones the deployment scripts use or the watchdog will be watching a
# different service from the one that is installed.
PANCRA_BIN='$PANCRA_BIN'
PANCRA_PID='$PANCRA_PID'
PANCRA_LOG='$PANCRA_LOG'
PANCRA_READY_LINE='$PANCRA_READY_LINE'
PANCRA_DOWN='$PANCRA_DOWN'
PANCRA_LOCK='$PANCRA_LOCK'
PANCRA_LOCK_STALE='$PANCRA_LOCK_STALE'
PANCRA_SUPERVISE_PID='$PANCRA_SUPERVISE_PID'
PANCRA_SUPERVISE_LOG='$PANCRA_SUPERVISE_LOG'
PANCRA_SUPERVISE_INTERVAL='$PANCRA_SUPERVISE_INTERVAL'
PANCRA_SUPERVISE_READY='$PANCRA_SUPERVISE_READY'
PANCRA_SUPERVISE_BACKOFF='$PANCRA_SUPERVISE_BACKOFF'
PANCRA_SUPERVISE_GRACE='$PANCRA_SUPERVISE_GRACE'
pancra_start_template() {
   cat <<'PANCRA_START_EOF'
$(start_template)
PANCRA_START_EOF
}
EOF
}

# THE BLOCK THAT GOES INTO THE BOARD'S OWN STARTUP SCRIPT, between sentinels so
# that installing it twice replaces it instead of stacking up. Ten deploys must
# not leave ten launch lines in somebody else's boot script.
supervisor_hook_block() {
   cat <<EOF
# >>> pancra supervisor >>>
# Installed by srv/deploy (deploy.sh). Everything between these two markers is
# replaced by the next deploy, so edits here are lost; change
# srv/deploy/pancra.conf instead.
#
# It starts the watchdog, which starts the sync server if it is not running.
# Guarded and detached: if the watchdog is missing this line does nothing and
# the rest of this script still runs, and it never blocks the boot.
$(supervisor_block)
# <<< pancra supervisor <<<
EOF
}

# Is a watchdog alive on the board right now? Asked of the board, by pid, not
# inferred from "we launched one" -- which is the difference between testing
# that a file was written and testing that a service is supervised.
supervisor_running() {
   $SSH "$PANCRA_HOST" "sh -s" >/dev/null 2>&1 <<EOF
set -eu
pid=\$(cat '$PANCRA_SUPERVISE_PID' 2>/dev/null | tr -dc '0-9')
[ -n "\$pid" ]
kill -0 "\$pid"
EOF
}

# ---- INSTALL IT ---------------------------------------------------------
#
# supervisor_install <op-id>
#
# 0 when the board is supervised afterwards (or when the deployment has said,
# on purpose, that it is not to be). 1 when supervision was asked for and could
# not be established -- which the caller reports LOUDLY but does not treat as a
# failed deployment: the service is up, and refusing a good deploy over its
# safety net would be the mechanism making the outage.
supervisor_install() {
   si_op=${1:-$$}
   case "${PANCRA_SUPERVISOR:-}" in
      none)
         echo "deploy: NOTHING SUPERVISES THIS SERVER (PANCRA_SUPERVISOR=none)." >&2
         echo "  If it exits, it stays exited; if the board reboots, it does" >&2
         echo "  not come back. That is a choice this deployment has made on" >&2
         echo "  purpose -- set PANCRA_SUPERVISOR=watchdog to have it looked" >&2
         echo "  after, or point your own service manager at" >&2
         echo "  $PANCRA_SUPERVISE (never at the server directly: the start" >&2
         echo "  command has one definition, in srv/deploy/start.sh)." >&2
         return 0
         ;;
      watchdog) ;;
      *)
         echo "deploy: PANCRA_SUPERVISOR='${PANCRA_SUPERVISOR:-}' is not a" >&2
         echo "  mechanism this repository knows how to install, so NOTHING" >&2
         echo "  is supervising the server. Use watchdog or none." >&2
         return 1
         ;;
   esac

   # THE SCRIPT, COPIED BESIDE AND RENAMED, exactly as the executable is: a
   # transfer that dies halfway must not leave a half-written watchdog that the
   # boot hook will then run.
   $PANCRA_SCP "$HERE/srv/deploy/supervise.sh" \
      "$PANCRA_HOST:$PANCRA_SUPERVISE.new-$si_op" || {
      echo "deploy: could not copy the watchdog to $PANCRA_HOST." >&2
      return 1
   }
   supervisor_env_block |
      $SSH "$PANCRA_HOST" "cat > '$PANCRA_SUPERVISE_ENV.new-$si_op'" || {
      echo "deploy: could not write $PANCRA_SUPERVISE_ENV on $PANCRA_HOST." >&2
      return 1
   }
   if ! $SSH "$PANCRA_HOST" "sh -s" <<EOF
set -eu
chmod +x '$PANCRA_SUPERVISE.new-$si_op'
mv '$PANCRA_SUPERVISE.new-$si_op' '$PANCRA_SUPERVISE'
mv '$PANCRA_SUPERVISE_ENV.new-$si_op' '$PANCRA_SUPERVISE_ENV'
EOF
   then
      echo "deploy: could not install the watchdog on $PANCRA_HOST." >&2
      return 1
   fi

   si_boot=0
   supervisor_boot_install || si_boot=1

   # ---- AND START IT NOW ------------------------------------------------
   #
   # Not only at the next boot. The deploy has just restarted the service and
   # this is the moment the board is known-good; waiting for a reboot to begin
   # supervising means the first crash before that reboot is unsupervised, and
   # on a board that has been up for eight months that is every crash.
   #
   # Launching a second one is harmless: supervise.sh claims a directory and
   # the loser says so and exits 0.
   $SSH "$PANCRA_HOST" "sh -s" <<EOF || true
$(supervisor_block)
EOF
   # ...AND IT IS ASKED WHETHER IT IS THERE. A launch is not a service. The
   # first version of this reported "supervision installed" on the strength of
   # having run a command, and a watchdog that had exited immediately -- an env
   # file from an older deploy missing a variable, a board where the copy
   # landed unreadable -- looked exactly the same from here.
   si_i=0
   while [ $si_i -lt 15 ]; do
      if supervisor_running; then
         printf 'deploy: supervised: %s watches %s\n' \
            "$PANCRA_SUPERVISE" "$PANCRA_BIN"
         # THE BOOT HALF IS PART OF THE VERDICT. A watchdog that is running
         # now and will not be running after the next power cut is half a
         # supervisor, and the caller has to hear about the half that is
         # missing rather than "supervised".
         if [ "${si_boot:-0}" = 1 ]; then
            return 1
         fi
         return 0
      fi
      sleep 1
      si_i=$((si_i + 1))
   done
   echo "deploy: THE WATCHDOG WAS INSTALLED AND IS NOT RUNNING." >&2
   echo "  The service itself is fine -- this deploy started it and checked" >&2
   echo "  it -- but nothing will start it again if it exits, and nothing" >&2
   echo "  will start it after a reboot. Ask the board why:" >&2
   echo "    $PANCRA_SUPERVISE status $PANCRA_SUPERVISE_ENV" >&2
   echo "    tail $PANCRA_SUPERVISE_LOG" >&2
   return 1
}

# ---- ...AND AFTER A REBOOT ----------------------------------------------
#
# ONE GUARDED BLOCK IN THE BOARD'S OWN STARTUP SCRIPT, which is the only kind
# of boot enablement that works on a board with no service manager. Which
# script that is cannot be discovered from here -- it is PANCRA_BOOT_HOOK, and
# an undeclared one is reported rather than guessed.
#
# INSERTED AT THE TOP, after any `#!` line, and this is the detail that decides
# whether any of it works: a startup script that ends by handing its process
# over with `exec` -- which is exactly what the board's does, to its sensor
# logger -- never reaches a line appended to the end. An appended block is a
# boot enablement that is present in the file, visible in review, and dead.
supervisor_boot_install() {
   case "${PANCRA_BOOT_HOOK:-unset}" in
      "" | unset)
         echo "deploy: NOTHING STARTS THIS SERVER AFTER A REBOOT." >&2
         echo "  The watchdog is running and will restart the service if it" >&2
         echo "  exits, but it is a process like any other: a reboot ends it" >&2
         echo "  too, and no startup script on the board mentions it." >&2
         echo "  Set PANCRA_BOOT_HOOK to a script the board runs at boot" >&2
         echo "  (on a BusyBox board that is usually the user script the" >&2
         echo "  init chain ends in, not an /etc/init.d file), and re-run." >&2
         return 1
         ;;
   esac
   sb_out=$($SSH "$PANCRA_HOST" "sh -s" 2>&1 <<EOF
set -eu
hook='$PANCRA_BOOT_HOOK'
if [ ! -f "\$hook" ]; then
   echo NOHOOK
   exit 0
fi
work=\$hook.pancra-work
cat > "\$work.block" <<'PANCRA_HOOK_BLOCK'
$(supervisor_hook_block)
PANCRA_HOOK_BLOCK
# THE PREVIOUS CONTENTS, KEPT. This file belongs to the board, not to us --
# on the target it is the script that also starts the board's other service --
# and it is rewritten in place below rather than replaced, so that its owner,
# its mode and anything else pointing at it survive. In-place means a failure
# halfway leaves it truncated, which is a board that does not boot properly, so
# the copy beside it is not a nicety.
cp "\$hook" "\$hook.pancra-prev"
sed '/^# >>> pancra supervisor >>>/,/^# <<< pancra supervisor <<</d' \
   "\$hook" > "\$work.stripped"
first=\$(head -n 1 "\$work.stripped" 2>/dev/null || true)
case "\$first" in
   '#!'*)
      { printf '%s\n' "\$first"
        cat "\$work.block"
        tail -n +2 "\$work.stripped"; } > "\$work.out"
      ;;
   *) cat "\$work.block" "\$work.stripped" > "\$work.out" ;;
esac
cat "\$work.out" > "\$hook"
rm -f "\$work.block" "\$work.stripped" "\$work.out"
grep -c '^# >>> pancra supervisor >>>' "\$hook"
EOF
)
   case "$sb_out" in
      NOHOOK*)
         echo "deploy: PANCRA_BOOT_HOOK names $PANCRA_BOOT_HOOK, which is not" >&2
         echo "  on the board -- so NOTHING STARTS THIS SERVER AFTER A" >&2
         echo "  REBOOT. It was not created: a startup script this" >&2
         echo "  deployment invented is one the board's init never runs, and" >&2
         echo "  a file that looks like boot enablement and is not is worse" >&2
         echo "  than an honest gap. Name the script the board really runs." >&2
         return 1
         ;;
      1) ;;
      *)
         echo "deploy: the boot hook $PANCRA_BOOT_HOOK was not installed" >&2
         echo "  cleanly (the board said: $sb_out), so the service may not" >&2
         echo "  come back after a reboot. The file as it was before this" >&2
         echo "  attempt is at $PANCRA_BOOT_HOOK.pancra-prev." >&2
         return 1
         ;;
   esac
   printf 'deploy: boot: %s starts the watchdog\n' "$PANCRA_BOOT_HOOK"
   return 0
}
